server:
  port: 8083

spring:
  application:
    name: mood-tracker-service

  datasource:
    url: jdbc:mysql://localhost:3306/mentelibre_mood
    username: root
    password:             # tu contraseña si aplica
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
