server:
  port: 8082

spring:
  application:
    name: user-profile-service

  datasource:
    url: jdbc:mysql://localhost:3306/mentelibre_user_profile
    username: root
    password: root  # o la contraseña que uses
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
