server:
  port: 8085

spring:
  application:
    name: notifications-service

  datasource:
    url: jdbc:mysql://localhost:3306/mentelibre_notifications
    username: root
    password:           # tu contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
